### ISSUE TITLE
Makefile: no such file or directory

### ISSUE THREAD

**Issue by shenki** [open-power/occ#11]
When building I noticed the following warnings emitted by make

```
/home/joel/op-build/output/build/occ-1093bf945e6c22650ca0b83da2347ee7d21cbe41/src/tracepp/tracepp /home/joel/op-build/output/host/usr/bin/powerpc64le-buildroot-linux-gnu-gcc -c -g -Wall -fsigned-char -msoft-float -m32 -mbig-endian -mcpu=405 -mmultiple -mstring -meabi -msdata=eabi -ffreestanding -fno-common -fno-inline-functions-called-once -pipe -Wa,-m405 -Os -I../ssx -I../lib  -I./incl  -I./trac  -I./async -I./errl -I./gpe  -I./thread -I./aplt -I./aplt/incl -I./rtls -I./dcom -I./sensor -I./pss -I./proc -I./cent -I./cmdh -I./amec -I.  -I../occ  -I../../occ  -I./timer -I./firdata -I../ssx -I../ppc32 -I../ppc405 -I../pgp -I../pgp/registers -I../../lib  -DSIMICS_ENVIRONMENT=0 -DSSX_TIMER_SUPPORT=1  -DSSX_THREAD_SUPPORT=1  -DPPC405_MMU_SUPPORT=1 -DOCC_FIRMWARE=1 -DSIMICS_MAGIC_PANIC=1 -DOCC=1 -DNONCACHEABLE_SUPPORT=1 -DUSE_SSX_APP_CFG_H=1      -DPGAS_PPC=1 -DCONFIGURE_PTS_SLW=0 -o ppc405_mmu.o ppc405_mmu.c
make -I ../pgp -C ../ppc32
Makefile:29: ppc32_gcc.d: No such file or directory
Makefile:29: div64.d: No such file or directory
Makefile:29: savegpr.d: No such file or directory
```

**Comment by wilbryan** [comment]
Those files are not necessary and those messages can be ignored.

**Comment by shenki** [comment]
Having errors like this as part of the build process hide real errors when they occur. We would like to see them cleaned up, as they reflect on the quality of our software.

**Comment by stewart-ibm** [comment]
I very much agree with @shenki on this one - we're keen to move to a point where all the open power projects build clean (with -Wall and extras) and it's easy to spot anything new that comes in.

At some point soon, we're going to hook up a "build with top of tree toolchain" CI job with the purpose of testing both all the open power software and the toolchain itself. Hard to spot errors just make it harder to see what broke what.
