### ISSUE TITLE
Uses BE flags when building with LE compiler

### ISSUE THREAD

**Issue by shenki** [open-power/occ#12]
```
/home/joel/op-build/output/build/occ-1093bf945e6c22650ca0b83da2347ee7d21cbe41/src/tracepp/tracepp /home/joel/op-build/output/host/usr/bin/powerpc64le-buildroot-linux-gnu-gcc -c -g -Wall -fsigned-char -msoft-float -m32 -mbig-endian -mcpu=405 -mmultiple -mstring -meabi -msdata=eabi -ffreestanding -fno-common -fno-inline-functions-called-once -pipe -Wa,-m405 -Os -I../ssx -I../lib  -I./incl  -I./trac  -I./async -I./errl -I./gpe  -I./thread -I./aplt -I./aplt/incl -I./rtls -I./dcom -I./sensor -I./pss -I./proc -I./cent -I./cmdh -I./amec -I.  -I../occ  -I../../occ  -I./timer -I./firdata -I../ssx -I../ppc32 -I../ppc405 -I../pgp -I../pgp/registers -I../../lib  -DSIMICS_ENVIRONMENT=0 -DSSX_TIMER_SUPPORT=1  -DSSX_THREAD_SUPPORT=1  -DPPC405_MMU_SUPPORT=1 -DOCC_FIRMWARE=1 -DSIMICS_MAGIC_PANIC=1 -DOCC=1 -DNONCACHEABLE_SUPPORT=1 -DUSE_SSX_APP_CFG_H=1      -DPGAS_PPC=1 -DCONFIGURE_PTS_SLW=0 -o ppc405_mmu.o ppc405_mmu.c
make -I ../pgp -C ../ppc32
Makefile:29: ppc32_gcc.d: No such file or directory
Makefile:29: div64.d: No such file or directory
Makefile:29: savegpr.d: No such file or directory
cc1: warning: -mmultiple is not supported on little endian systems
cc1: warning: -mstring is not supported on little endian systems
cc1: warning: -mmultiple is not supported on little endian systems
cc1: warning: -mstring is not supported on little endian systems
cc1: warning: -mmultiple is not supported on little endian systems
cc1: warning: -mstring is not supported on little endian systems
```

**Comment by williamspatrick** [comment]
How is this OCCs problem?  The OCC is targeting a ppc405, which is BE. You need to use a cross-compiler and not your native LE compiler. 

Patrick

**Comment by shenki** [comment]
On Tue, Feb 23, 2016 at 10:34 PM, Patrick Williams <notifications@github.com
> wrote:

> How is this OCCs problem? The OCC is targeting a ppc405, which is BE. You
> need to use a cross-compiler and not your native LE compiler.


This is op-build, not my native LE compiler

**Comment by williamspatrick** [comment]
I still don't understand the problem with regards to OCC. You see -mbig-endian as one of the complained about options. Both Hostboot and OCC need a big endian  compiler.  Something is wrong with your build root update if these gcc options don't work. 

Patrick

**Comment by williamspatrick** [comment]
It is -mmultiple and -mstring that is failing and not big endian itself. Even still, these are directives to use a group of instructions that should be available when targeting ppc405 (and are probably required by OCC code for optimization reasons). I still contend something is wrong with gcc. 

I suspect there is a bug when compiling a multi-target, little-endian compiler that it disables a set of big-endian only options. This is wrong behavior on the part of gcc as the target machine does indeed support these instructions.

**Comment by shenki** [comment]
@williamspatrick Right, I think you hit the nail on the head there - it's a bad warning generated by our frankencompiler. I realise it's not an issue with the OCC firmware itself but lets track it here. I'm keen to clean up the op-build so we don't have any "expected failures".

@jk-ozlabs, have you looked into this at all?

**Comment by williamspatrick** [comment]
Please create op-build issue and assign to @jk-ozlabs.  He isn't a member of the OCC team so I cannot assign him this issue and he seems unresponsive to the previous inquiry.
