### ISSUE TITLE
LICENSE file location is inconsistent between branches, breaks legal-info target

### ISSUE THREAD

**Issue by sammj** [open-power/occ#16]
On master_p8 the LICENSE and README files are under the src/ directory, but on master they are simply in the root directory. However in the occ.mk file in op-build we simply have
```
OCC_LICENSE_FILES = src/LICENSE
```
Which fails when building with master.

A single location should be decided on so that the build doesn't break when building the legal-info buildroot target.

**Comment by wilbryan** [comment]
Do we need to sync them to the same location or is there an easy way to differentiate between the branches? If not, we can probably change the location for P8.

**Comment by sammj** [comment]
True you could handle the difference in much the same way as `OCC_VERSION` is handled in occ.mk - depends on what is easier/neater.

**Comment by wilbryan** [comment]
Fixed with https://github.com/open-power/op-build/pull/968
