### ISSUE TITLE
Missing include in tracepp.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/occ#2]
Please merge this patch into the occ codebase and create an op-build pull request to update the occ version and remove the patch from op-build.

https://github.com/open-power/op-build/blob/master/openpower/package/occ/occ-0001-Fix-compile-fail-in-tracepp.patch

**Comment by sbroylesibm** [comment]
Fixed by 6a2a3dd2c8f2484b920bf6f1f25003bd3d428557 on 12/16/2014
