### ISSUE TITLE
Does the OCC module of Open-Power P10 have FIR data collection function?

### ISSUE THREAD

**Issue by Theo0208** [open-power/occ#31]
In OCC module of open-power P9, after the checkstop is triggered, the  "ipc_fir_collection" function will be called to realize the collection of "FIR data". Excuse me, Is there any similar function in OCC module of open-power P10 to realize the collection of "FIR data"? If so, I want to know where it is, If not, how to generate GARD records in Hostboot module? Thanks.

**Comment by cjcain** [comment]
OCC does not do the fir collection in p10.  I believe that functionality would be part of hostboot for p10.

**Comment by Theo0208** [comment]
Thank you very much for your reply. But I didn't find any code related to FIR data collection in  hostboot for p10. In addition, Hostboot will stop running immediately after the checkstop is triggered, so it seems that hostboot should not perform FIR data collection.

**Comment by zane131** [comment]
The OCC/Hostboot design we used for P9 has been replaced. System checkstop analysis for P10 Power systems is handled by [openpower-hw-diags](https://github.com/openbmc/openpower-hw-diags), which is run in OpenBMC firmware.

**Comment by Theo0208** [comment]
> The OCC/Hostboot design we used for P9 has been replaced. System checkstop analysis for P10 Power systems is handled by [openpower-hw-diags](https://github.com/openbmc/openpower-hw-diags), which is run in OpenBMC firmware.
Thank you very much for your answer to this question.
