### ISSUE TITLE
occ fails to build with GCC 5.2 or 5.3

### ISSUE THREAD

**Issue by deece** [open-power/occ#8]
When building with GCC 5, occ fails to link with the following error:
linkscript:28 cannot move location counter backwards (from 00000000fff8122c to 00000000fff80c00)

From the GCC 5.3 build:
$ objdump -h ppc405_irq_core.o

ppc405_irq_core.o:     file format elf32-powerpc

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         00000404  00000000  00000000  00000034  2**2
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE
...

$ objdump -h ppc405_core.o

ppc405_core.o:     file format elf32-powerpc

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         00000600  00000000  00000000  00000034  2**2
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE
...

From the GCC 4.9 build:
$ objdump -h ppc405_irq_core.o

ppc405_irq_core.o:     file format elf32-powerpc

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         00000174  00000000  00000000  00000034  2**2
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE

$ objdump -h ppc405_core.o

ppc405_core.o:     file format elf32-powerpc

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         00000198  00000000  00000000  00000034  2**2
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE

The text sections are substantially larger in GCC 5.x, resulting in them overflowing the space allocated for them in linkocc.cmd

**Comment by deece** [comment]
The GCC 5.x object contains many more symbols than GCC 4.9:

GCC 5.3:
$ ~/src/op-build/output/host/usr/bin/powerpc64le-linux-objdump --disassemble ppc405_irq_core.o | grep -E :$
Disassembly of section .text:
00000000 <islower>:
0000002c <isupper>:
00000058 <isalpha>:
00000088 <isdigit>:
000000b4 <isalnum>:
000000e4 <isxdigit>:
00000110 <iscntrl>:
00000138 <isspace>:
00000164 <isprint>:
00000190 <isgraph>:
000001cc <ispunct>:
000001f8 <tolower>:
00000238 <toupper>:
00000278 <ssx_irq_enable>:
000002a4 <ssx_irq_disable>:
000002cc <ssx_interrupt_disable>:
00000340 <ssx_machine_context_set>:
0000037c <ssx_machine_context_get>:
000003b4 <ssx_current>:
000003bc <__ppc405_default_irq_handler>:
000003e0 <__ppc405_phantom_irq_handler>:


GCC 4.9:
$ ~/src/op-build/output/host/usr/bin/powerpc64le-linux-objdump --disassemble ppc405_irq_core.o | grep -E :$
Disassembly of section .text:
00000000 <ssx_irq_enable>:
00000034 <ssx_irq_disable>:
00000064 <ssx_irq_status_clear>:
00000098 <ssx_irq_status_get>:
000000cc <ssx_irq_status_set>:
0000012c <__ppc405_default_irq_handler>:
00000150 <__ppc405_phantom_irq_handler>:

**Comment by deece** [comment]
It looks like the problem arises due to those symbols being marked as "extern inline", which is somewhat contradictory in my mind. I think it is perfectly reasonable for GCC 5 to emit symbols for them, since they have been declared with external linkage.

**Comment by wilbryan** [comment]
This should be fixed by using the gnu89 standard, in https://github.com/open-power/occ/commit/72544469d2e83fca6d7ef20a01661a6710077c3b
